-- Clinicas
INSERT INTO TB_CLINICAS (NOME_CLINICA, ENDERECO) VALUES ('Clínica Online', NULL);
INSERT INTO TB_CLINICAS (NOME_CLINICA, ENDERECO) VALUES ('Clínica São José', 'Rua das Flores, 123, São Paulo - SP');
INSERT INTO TB_CLINICAS (NOME_CLINICA, ENDERECO) VALUES ('Clínica Vida Saudável', 'Avenida Brasil, 456, Rio de Janeiro - RJ');
INSERT INTO TB_CLINICAS (NOME_CLINICA, ENDERECO) VALUES ('Clínica Bem Estar', 'Rua da Paz, 789, Belo Horizonte - MG');
INSERT INTO TB_CLINICAS (NOME_CLINICA, ENDERECO) VALUES ('Clínica Saúde Total', 'Rua Principal, 101, Porto Alegre - RS');
INSERT INTO TB_CLINICAS (NOME_CLINICA, ENDERECO) VALUES ('Clínica Cuidar Mais', 'Avenida Central, 202, Salvador - BA');
INSERT INTO TB_CLINICAS (NOME_CLINICA, ENDERECO) VALUES ('Clínica Esperança', 'Rua do Sol, 303, Curitiba - PR');
INSERT INTO TB_CLINICAS (NOME_CLINICA, ENDERECO) VALUES ('Clínica Harmonia', 'Avenida das Palmeiras, 404, Recife - PE');
INSERT INTO TB_CLINICAS (NOME_CLINICA, ENDERECO) VALUES ('Clínica Novo Horizonte', 'Rua das Acácias, 505, Fortaleza - CE');
INSERT INTO TB_CLINICAS (NOME_CLINICA, ENDERECO) VALUES ('Clínica Viva Bem', 'Avenida Independência, 606, Manaus - AM');
INSERT INTO TB_CLINICAS (NOME_CLINICA, ENDERECO) VALUES ('Clínica Mais Saúde', 'Rua Verde, 707, Florianópolis - SC');

-- Medicos
INSERT INTO TB_MEDICO (NOME_PROFISSIONAL, CRM, CRM_ESTADO, ESPECIALIDADE) VALUES ('Dr. João Silva', 123456, 'SP', 'Psicologia');
INSERT INTO TB_MEDICO (NOME_PROFISSIONAL, CRM, CRM_ESTADO, ESPECIALIDADE) VALUES ('Dra. Maria Oliveira', 789012, 'RJ', 'Psicologia');
INSERT INTO TB_MEDICO (NOME_PROFISSIONAL, CRM, CRM_ESTADO, ESPECIALIDADE) VALUES ('Dr. Pedro Santos', 345678, 'MG', 'Psicologia');
INSERT INTO TB_MEDICO (NOME_PROFISSIONAL, CRM, CRM_ESTADO, ESPECIALIDADE) VALUES ('Dra. Ana Costa', 901234, 'BA', 'Psicologia');
INSERT INTO TB_MEDICO (NOME_PROFISSIONAL, CRM, CRM_ESTADO, ESPECIALIDADE) VALUES ('Dr. Lucas Almeida', 567890, 'RS', 'Psicologia');
INSERT INTO TB_MEDICO (NOME_PROFISSIONAL, CRM, CRM_ESTADO, ESPECIALIDADE) VALUES ('Dra. Sofia Pereira', 234567, 'PR', 'Psicologia');

-- Usuario
INSERT INTO TB_PERFIL_USUARIO ( NOME, CPF, EMAIL, SENHA, ENDERECO, CEP, CIDADE, ESTADO, UF, TELEFONE, DATA_DE_NASCIMENTO, PACIENTE, FAMILIAR) VALUES ('João da Silva', '12345678901', 'joao.silva@email.com', '$2a$10$ebcF1he3afW5caAeCwVqd.pxAA2KdOecpJJKIWTsc/wcucmoQIMAK', 'Rua das Flores, 123', '12345678', 'São Paulo', 'São Paulo', 'SP', '11999998888', '1985-05-20', TRUE, FALSE);
